version: '3'
services:
  db:
    image: "wnameless/oracle-xe-11g-r2"
    environment:
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ALLOW_REMOTE=true
    ports:
      - 1521:1521
    volumes:
      - ./oracle/init.sql:/docker-entrypoint-initdb.d/init.sql

  # service-registry:
  #   image: "035167628910.dkr.ecr.ap-southeast-1.amazonaws.com/fast-service-registry:latest"
  #   ports:
  #     - 8761:8761

  # rabbitmq:
  #   image: "bitnami/rabbitmq:latest"
  #   ports:
  #     - 15672:15672
  #     - 5672:5672
